apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: agent-memory-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      agent-memory-exporter: enabled
  podMetricsEndpoints:
    - port: agent-metrics
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
