#负责接收告警


#全局设置
global:
  resolve_timeout: 1m

#定义告警如何分发
route:
  receiver: recovery-controller
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 30s

#接收器列表
receivers:
  - name: recovery-controller
    webhook_configs:
      - url: "http://host.docker.internal:9000/alert"
        send_resolved: true